# Generated by Django 4.1.3 on 2023-01-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('BE', 'Beginner'), ('AD', 'Advanced'), ('EX', 'Expert')], default='BE', max_length=2),
        ),
    ]
