# Generated by Django 4.1.3 on 2023-01-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_profile_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='line total'),
        ),
        migrations.AlterField(
            model_name='ordershistory',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='total'),
        ),
    ]
