# Generated by Django 4.1.6 on 2023-02-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_cart_line_total_alter_ordershistory_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='total'),
        ),
    ]
