# Generated by Django 4.1.6 on 2023-02-09 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_ordershistory_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='line_total',
        ),
    ]
