# Generated by Django 4.1.6 on 2023-02-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_alter_cart_id_alter_orderline_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='order_lines',
            field=models.ManyToManyField(to='app_users.orderline', verbose_name='order line'),
        ),
    ]
