# Generated by Django 4.1.6 on 2023-02-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_alter_ordershistory_order_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='purchase price'),
            preserve_default=False,
        ),
    ]
