# Generated by Django 4.1.6 on 2023-02-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_orderline_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
