# Generated by Django 4.1.6 on 2023-02-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_alter_ordershistory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordershistory',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
